/*
 * PriceTable.java
 * Copyright (C) 2002 Klaus Rennecke.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

package net.sourceforge.fraglets.mtgo.trader;

import javax.swing.table.TableModel;
import javax.swing.JTable;

/**
 * Simple table display to show card prices.
 * @author marion@users.sourceforge.net
 */
public class PriceTable extends javax.swing.JPanel {
    
    /** Creates new form PriceTable */
    public PriceTable(TableModel model) {
        initComponents();
        setModel(model);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        tableScroll = new javax.swing.JScrollPane();
        priceTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        tableScroll.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        priceTable.setCellEditor(null);
        tableScroll.setViewportView(priceTable);

        add(tableScroll, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    public void setModel(TableModel model) {
        priceTable.setModel(model);
    }
    
    public TableModel getModel() {
        return priceTable.getModel();
    }
    
    public JTable getTable() {
        return priceTable;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane tableScroll;
    private javax.swing.JTable priceTable;
    // End of variables declaration//GEN-END:variables
    
}
