/*
 * TestForm.java
 *
 * Created on November 6, 2002, 12:25 PM
 */

package net.sourceforge.fraglets.yaelp.bean;

import java.net.URL;
import net.sourceforge.fraglets.yaelp.action.ActionContext;
import net.sourceforge.fraglets.yaelp.action.GenericAction;

/**
 *
 * @author  marion@users.sourceforge.net
 */
public class TestForm extends javax.swing.JFrame implements ActionContext {
    
    /** Creates new form TestForm */
    public TestForm() {
        initComponents();
        GenericAction.setActionContext(this, this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        yaelpMenuBar1 = new net.sourceforge.fraglets.yaelp.bean.YaelpMenuBar();

        setTitle("Testing");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        setJMenuBar(yaelpMenuBar1);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TestForm().show();
    }
    
    public String getApplicationName() {
        return "Test Form";
    }    
    
    public URL getResource(String localName) {
        return TestForm.class.getResource(localName);
    }
    
    public String getResourceString(String key) {
        return Defaults.getString(key);
    }
    
    public String getVersion() {
        return "$Revision: 1.1 $";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.sourceforge.fraglets.yaelp.bean.YaelpMenuBar yaelpMenuBar1;
    // End of variables declaration//GEN-END:variables
    
}
