/*
 * DateInput.java
 *
 * Created on 23. Juni 2001, 15:50
 */

package net.sourceforge.fraglets.yaelp;

/**
 *
 * @author  Klaus Rennecke
 */
public class DateInput extends javax.swing.JPanel {

    /** Creates new form DateInput */
    public DateInput(long time) {
        initComponents();
        add(javax.swing.Box.createGlue());
        setTime(time);
    }
    
    /** Creates new form DateInput */
    public DateInput() {
        this(System.currentTimeMillis());
    }
    
    public long getTime() {
        return java.sql.Date.valueOf
            (Integer.parseInt(yearField.getText())+"-"+
             Integer.parseInt(monthField.getText())+"-"+
             Integer.parseInt(dayField.getText())).getTime();
    }
    
    public void setLabel(String text) {
        label.setText(text);
    }
    
    public void setTime(long time) {
        String now = new java.sql.Date(time).toString();
        yearField.setText(now.substring(0, 4));
        yearField.selectAll();
        monthField.setText(now.substring(5, 7));
        monthField.selectAll();
        dayField.setText(now.substring(8, 10));
        dayField.selectAll();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        label = new javax.swing.JLabel();
        inputPanel = new javax.swing.JPanel();
        yearField = new javax.swing.JTextField();
        dash1 = new javax.swing.JLabel();
        monthField = new javax.swing.JTextField();
        dash2 = new javax.swing.JLabel();
        dayField = new javax.swing.JTextField();
        
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
        
        label.setText(java.util.ResourceBundle.getBundle("net/sourceforge/fraglets/yaelp/YaelpResources").getString("DateInput.label"));
        label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(label);
        
        inputPanel.setLayout(new javax.swing.BoxLayout(inputPanel, javax.swing.BoxLayout.X_AXIS));
        
        inputPanel.setBorder(javax.swing.UIManager.getBorder("TextField.border"));
        yearField.setToolTipText(java.util.ResourceBundle.getBundle("net/sourceforge/fraglets/yaelp/YaelpResources").getString("DateInput.year.tooltip"));
        yearField.setColumns(4);
        yearField.setFont(new java.awt.Font("DialogInput", 0, 12));
        yearField.setBorder(null);
        yearField.setMaximumSize(yearField.getPreferredSize());
        yearField.setMinimumSize(yearField.getPreferredSize());
        inputPanel.add(yearField);
        
        dash1.setText("-");
        dash1.setForeground(yearField.getForeground());
        dash1.setBackground(yearField.getBackground());
        dash1.setFont(yearField.getFont());
        dash1.setOpaque(true);
        inputPanel.add(dash1);
        
        monthField.setToolTipText(java.util.ResourceBundle.getBundle("net/sourceforge/fraglets/yaelp/YaelpResources").getString("DateInput.month.tooltip"));
        monthField.setColumns(2);
        monthField.setFont(new java.awt.Font("DialogInput", 0, 12));
        monthField.setBorder(null);
        monthField.setMaximumSize(monthField.getPreferredSize());
        monthField.setMinimumSize(monthField.getPreferredSize());
        inputPanel.add(monthField);
        
        dash2.setText("-");
        dash2.setForeground(yearField.getForeground());
        dash2.setBackground(yearField.getBackground());
        dash2.setFont(yearField.getFont());
        dash2.setOpaque(true);
        inputPanel.add(dash2);
        
        dayField.setToolTipText(java.util.ResourceBundle.getBundle("net/sourceforge/fraglets/yaelp/YaelpResources").getString("DateInput.day.tooltip"));
        dayField.setColumns(2);
        dayField.setFont(new java.awt.Font("DialogInput", 0, 12));
        dayField.setBorder(null);
        dayField.setMaximumSize(dayField.getPreferredSize());
        dayField.setMinimumSize(dayField.getPreferredSize());
        inputPanel.add(dayField);
        
        add(inputPanel);
        
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JTextField yearField;
    private javax.swing.JLabel dash1;
    private javax.swing.JTextField monthField;
    private javax.swing.JLabel dash2;
    private javax.swing.JTextField dayField;
    // End of variables declaration//GEN-END:variables

}
