/*
 * UpdateApplet.java
 *
 * Created on December 2, 2002, 11:35 PM
 */

package net.sourceforge.fraglets.yaelp;

/**
 *
 * @author  marion@users.sourceforge.net
 */
public class UpdateApplet extends javax.swing.JApplet {
    
    /** Creates new form UpdateApplet */
    public UpdateApplet() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        updateWizard = new net.sourceforge.fraglets.yaelp.UpdateWizard();

        getContentPane().add(updateWizard, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.sourceforge.fraglets.yaelp.UpdateWizard updateWizard;
    // End of variables declaration//GEN-END:variables
    
}
