/*
 * UpdateApplet.java
 * Copyright (C) 2002 Klaus Rennecke.
 * Created on December 2, 2002, 11:35 PM
 */

package net.sourceforge.fraglets.yaelp;

/**
 * Applet capsule for UpdateWizard.
 *
 * <p>This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * <p>This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * <p>You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 * @author  marion@users.sourceforge.net
 */
public class UpdateApplet extends javax.swing.JApplet {
    
    /** Creates new form UpdateApplet */
    public UpdateApplet() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        net.sourceforge.fraglets.yaelp.UpdateWizard updateWizard;

        updateWizard = new net.sourceforge.fraglets.yaelp.UpdateWizard();

        getContentPane().add(updateWizard, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
