/*
 * YaelpApplet.java
 *
 * Created on August 10, 2002, 1:40 PM
 */

package net.sourceforge.fraglets.yaelp;

import java.awt.BorderLayout;

/**
 *
 * @author  marion@users.sourceforge.net
 */
public class YaelpApplet extends javax.swing.JApplet {
    
    /** Creates new form YaelpApplet */
    public YaelpApplet() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jButton1 = new javax.swing.JButton();

        jButton1.setText("Launch Yaelp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        new RosterFrame(true).show();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
    
}
